
e.cloud.altemista.fwk.core.workflow.exception.unsupported_operation=This operation is not supported with the current implementation provider
e.cloud.altemista.fwk.core.workflow.exception.process_definition_not_found=Process definition with ID {} not found
e.cloud.altemista.fwk.core.workflow.exception.process_instance_not_found=Process instance with ID {} not found
e.cloud.altemista.fwk.core.workflow.exception.task_not_found=Task with ID {} not found
e.cloud.altemista.fwk.core.workflow.exception.comment_not_found=Comment with ID {} not found
e.cloud.altemista.fwk.core.workflow.exception.invalid_process_instance_state=The process instance with ID {} was in an unexpected state
e.cloud.altemista.fwk.core.workflow.exception.invalid_task_state=The task with ID {} was in an unexpected state
e.cloud.altemista.fwk.core.workflow.exception.not_unique_task=Task with ID {} was not unique
