
e.cloud.altemista.fwk.common.cryptography.exception.no_keystore=The keystore information is required
e.cloud.altemista.fwk.common.cryptography.exception.no_keystore_resource=The resource location of the keystore is required
e.cloud.altemista.fwk.common.cryptography.exception.no_keystore_password=The password of the keystore is required
e.cloud.altemista.fwk.common.cryptography.exception.no_keystore_type=The type of the keystore is required

e.cloud.altemista.fwk.common.cryptography.exception.invalid_keystore_type=Keystore type {} not available
e.cloud.altemista.fwk.common.cryptography.exception.invalid_keystore_algorithm=The algorithm used to check the integrity of the keystore cannot be found
e.cloud.altemista.fwk.common.cryptography.exception.invalid_keystore_certificate=Any of the certificates in the keystore could not be loaded
e.cloud.altemista.fwk.common.cryptography.exception.io_exception=I/O or format problem with the keystore data

e.cloud.altemista.fwk.common.cryptography.exception.invalid_keymanager_algorithm=Algorithm {} not available
e.cloud.altemista.fwk.common.cryptography.exception.invalid_keymanager_keystore=Operation failed
e.cloud.altemista.fwk.common.cryptography.exception.invalid_keymanager_key=A key could not be recovered

e.cloud.altemista.fwk.common.cryptography.exception.invalid_trustmanager_algorithm=Algorithm {} not available
e.cloud.altemista.fwk.common.cryptography.exception.invalid_trustmanager_keystore=Operation failed

e.cloud.altemista.fwk.common.cryptography.exception.publickey_invalid_keystore=Keystore at {} uninitialized
e.cloud.altemista.fwk.common.cryptography.exception.publickey_notfound=No public key with alias {} found in the keystore at {}

e.cloud.altemista.fwk.common.cryptography.exception.privatekey_algorithm=The algorithm for recovering the key cannot be found
e.cloud.altemista.fwk.common.cryptography.exception.privatekey_invalid_key=The key could not be recovered
e.cloud.altemista.fwk.common.cryptography.exception.privatekey_invalid_keystore=Keystore at {} uninitialized
e.cloud.altemista.fwk.common.cryptography.exception.privatekey_notfound=No private key with alias {} found in the keystore at {}
